### ISSUE TITLE
Support for `StatefulSet`

### ISSUE THREAD

**Issue by DJAlPee** [ottimis/lens-version-update#3]
Thanks for this really helpful plugin!

"Unfortunately", I'm migrating most of my workloads from `Deployment` to `StatefulSet`, which is not supported by your plugin. Could you please add support for this resource type?

Support for other resource types, like `Pod`, `DaemonSet`, etc. might make sense, too... 😉

**Comment by mmoriani** [comment]
Hi, thanks for your request, i've added support for StatefulSets in 1.2.0 😊
